- name: Install docker and docker-compose
  hosts: all
  serial: 1
  max_fail_percentage: 10
  gather_facts: false
  remote_user: ubuntu
  become: yes
  roles: 
    - { role: docker }

- name: Run Docker Containers With compose
  hosts: all
  serial: 1
  max_fail_percentage: 10
  gather_facts: false
  become: yes
  remote_user: ubuntu
  vars_files:
  - vars.yml
  roles:
  - { role: swarm }

